version: '3.3'

services:
  eureka:
    build:
      context: ./eureka
      dockerfile: eureka/Dockerfile
    image: eureka
    container_name: eureka
    ports:
      - 8761:8761
    networks:
      - registry

  pricing:
    build:
      context: ./pricing
      dockerfile: pricing/Dockerfile
    depends_on:
      - eureka
    environment: 
      - eureka.client.serviceUrl.defaultZone = http://eureka:8761/eureka/
    image: pricing
    container_name: pricing
    ports:
      - 8082:8082
    networks:
      - registry

  boogle:
    build:
      context: ./maps
      dockerfile: maps/Dockerfile
    image: boogle
    container_name: boogle
    ports:
      - 9191:9191

#  vehicles:
#    build:
#      context: ./vehicles
#      dockerfile: vehicles/Dockerfile
#    depends_on:
#      - eureka
#      - boogle
#      - pricing
#    image: vehiclesapi
#    container_name: vehicles-api
#    ports:
#      - 8080:8080
#    networks:
#      - registry

networks:
  registry:
    driver: bridge
